services:
  mongodb:
    build:
      context: ./mongo_init
      dockerfile: Dockerfile
    container_name: source_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: raw_data
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/json_files
      - mongo_storage:/data/db

  postgres:
    image: postgres:17
    container_name: dest_postgres
    restart: always
    environment:
      POSTGRES_USER: user_analytics
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./python_script/sql/init_dump.sql:/docker-entrypoint-initdb.d/init.sql

  etl_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_runner
    depends_on:
      - mongodb
      - postgres
    environment:
      MONGO_HOST: source_mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password123
      MONGO_DB: raw_data
      POSTGRES_DB_HOST: dest_postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_USER: user_analytics
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: analytics_db
    volumes:
      - .:/app

volumes:
  postgres_storage:
  mongo_storage: